(function(g){var window=this;var V5=function(a){g.W.call(this,{G:"button",aa:["ytp-offline-slate-button","ytp-button"],J:[{G:"div",L:"ytp-offline-slate-button-icon",J:["{{icon}}"]},{G:"div",L:"ytp-offline-slate-button-text",J:["{{text}}"]}]});this.B=a;this.o=this.l=null;this.hide();this.T("click",this.C,this)},CAa=function(a,b){!a.l&&b&&b.toggleButtonRenderer?a.l=b.toggleButtonRenderer:b&&b.toggleButtonRenderer||(a.l=null);
W5(a)},W5=function(a){if(a.l){if(a.l.isToggled){var b=a.l.toggledText?g.VN(a.l.toggledText):"";
a.update({text:b,icon:DAa(a.l.toggledIcon)})}else b=a.l.defaultText?g.VN(a.l.defaultText):"",a.update({text:b,icon:DAa(a.l.defaultIcon)});a.show()}else a.hide()},DAa=function(a){if(!a)return null;
switch(a.iconType){case "NOTIFICATIONS_NONE":return g.yV?{G:"div",aa:["ytp-icon","ytp-icon-notifications-none"]}:{G:"svg",U:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},J:[{G:"path",U:{d:"M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.63-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.64 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2zm-2 1H8v-6c0-2.48 1.51-4.5 4-4.5s4 2.02 4 4.5v6z"}}]};case "NOTIFICATIONS_ACTIVE":return g.Doa();default:return null}},X5=function(a){g.W.call(this,
{G:"div",
L:"ytp-offline-slate",J:[{G:"div",L:"ytp-offline-slate-bar",J:[{G:"span",L:"ytp-offline-slate-icon",J:[g.yV?{G:"div",aa:["ytp-icon","ytp-icon-live-icon"]}:{G:"svg",U:{fill:"#fff",height:"100%",viewBox:"0 0 24 24",width:"100%"},J:[{G:"path",U:{d:"M16.94 6.91l-1.41 1.45c.9.94 1.46 2.22 1.46 3.64s-.56 2.71-1.46 3.64l1.41 1.45c1.27-1.31 2.05-3.11 2.05-5.09s-.78-3.79-2.05-5.09zM19.77 4l-1.41 1.45C19.98 7.13 21 9.44 21 12.01c0 2.57-1.01 4.88-2.64 6.54l1.4 1.45c2.01-2.04 3.24-4.87 3.24-7.99 0-3.13-1.23-5.96-3.23-8.01zM7.06 6.91c-1.27 1.3-2.05 3.1-2.05 5.09s.78 3.79 2.05 5.09l1.41-1.45c-.9-.94-1.46-2.22-1.46-3.64s.56-2.71 1.46-3.64L7.06 6.91zM5.64 5.45L4.24 4C2.23 6.04 1 8.87 1 11.99c0 3.13 1.23 5.96 3.23 8.01l1.41-1.45C4.02 16.87 3 14.56 3 11.99s1.01-4.88 2.64-6.54z"}},
{G:"circle",U:{cx:"12",cy:"12",r:"3"}}]}]},{G:"span",L:"ytp-offline-slate-buttons"},{G:"span",L:"ytp-offline-slate-messages",J:[{G:"div",L:"ytp-offline-slate-main-text",J:["{{maintext}}"]},{G:"div",L:"ytp-offline-slate-subtitle-text",J:["{{subtitletext}}"]}]}]},{G:"div",L:"ytp-offline-slate-final-day",J:[{G:"div",L:"ytp-offline-slate-final-day-line-1",J:["Dawn of"]},{G:"div",L:"ytp-offline-slate-final-day-line-2",J:["The Final Day"]},{G:"div",L:"ytp-offline-slate-final-day-line-3",J:["-24 Hours Remain-"]}]}]});
this.o=a;this.A=this.l=null;this.B=new g.Yt(this.D,1E3,this);this.O(a,"presentingplayerstatechange",this.F);this.O(a,"livestatedata",this.C);this.hide();a=this.o.ea();a.getPlayerResponse()&&(a=a.getPlayerResponse().playabilityStatus)&&this.C(a)},Y5=function(a,b,c){if(b){var d=void 0!=b.subtitleText?g.VN(b.subtitleText):"";
b=c?c:void 0!=b.mainText?g.VN(b.mainText):"";a.update({maintext:b,subtitletext:d});g.T(a.element,"ytp-offline-slate-single-text-line",!d)}},$5=function(a){g.rV.call(this,a);
this.H=!1;this.I=0;this.F=!1;this.l=window.NaN;this.o=this.A=null;this.B=!1;this.D=null;this.K=-(new g.po).getTimezoneOffset();this.C=new g.GF(this);g.M(this,this.C);var b=this.g.ea();if(b.za){var c=g.Y(this.g);g.EL()?!c.experiments.g("live_fresca_v2")||!g.jM(c)&&g.tM(c)||(this.H=this.B=!0,this.D=new X5(this.g),g.M(this,this.D),g.lV(this.g,this.D.element,4),(b=b.getPlayerResponse())&&b.playabilityStatus&&(this.o=b.playabilityStatus),this.o?(b=EAa(this.o.liveStreamability&&this.o.liveStreamability.liveStreamabilityRenderer))?
Z5(this,b):Z5(this,7500):Z5(this,1E3)):g.hU(this.g.app.o,"html5.unsupportedlive","YTP_HTML5_NO_AVAILABLE_FORMATS_FALLBACK","nolive.1")}this.C.O(a,"heartbeatparams",this.LL);this.C.O(a,"presentingplayerstatechange",this.ML);this.C.O(a,"videoplayerreset",this.sT);this.C.O(a,"crn_heartbeat",this.KL);this.B&&this.o&&FAa(this,this.o);b=new g.nQ(1E3,0x7ffffffffffff,{priority:0,namespace:"heartbeat"});g.gV(a,[b])},GAa=function(a){a=a.g.ea();
return!!g.hO(a)&&!a.rs},a6=function(a){var b=a.g.ea();
return GAa(a)?!!a.A:!!b.heartbeatToken},Z5=function(a,b){if(!a.l&&a.H){var c=a.g.ea();
if(a6(a)||c.za)void 0==b&&(b=a.F?a.B?7500:a.A?1E3*a.A.interval:a.g.ea().heartbeatInterval||6E4:1E3),a.l=g.TD((0,g.z)(a.xU,a),b)}},FAa=function(a,b){var c=b.liveStreamability&&b.liveStreamability.liveStreamabilityRenderer,d=!(!c||!c.switchStreamsImmediately),e=EAa(c),f=a.g.ea();
if(g.UU(a.g).kb()&&!g.pO(f)&&!a.g.isPeggedToLive()&&!d)return e;var k=(d=c&&c.streamTransitionEndpoint&&c.streamTransitionEndpoint.watchEndpoint)&&d.videoId;if(k)return g.l0(a.g.app,k,void 0,void 0,!0,!0,d),e;if("OK"==b.status.toUpperCase()){if(!f.hlsvp&&!f.Ud||a.o&&c&&c.broadcastId!=a.o.liveStreamability.liveStreamabilityRenderer.broadcastId)return c={video_id:f.videoId},f.isLiveDestination&&(c.is_live_destination="1"),a.g.Do(c),e;g.kV(a.g,"heartbeat")}return e},EAa=function(a){var b=0;
a&&a.pollDelayMs&&(a=(0,window.parseInt)(a.pollDelayMs,10))&&(b=a);return b},b6=function(a,b,c){if(a.l){a.l=window.NaN;
a.I++;var d=a.g.ea();(d.heartbeatSoftFail?0:a.I>=(a.A?a.A.g:d.heartbeatRetries||5))?(b=b?"heartbeat.net":"heartbeat.servererror",(d=a.g.ea())&&d.za?(d=g.V("YTP_ERROR_STREAM_LICENSE_NOT_FOUND"),g.hU(a.g.app.o,b,d,c)):(d=g.V("YTP_ERROR_LICENSE"),g.hU(a.g.app.o,b,d,c))):Z5(a)}},c6=function(a){a.I=0;
a.l&&(g.VD(a.l),a.l=window.NaN);a.F=!1},HAa=function(a){try{var b=g.Xw(a);
return null!=b?b:null}catch(c){return null}};g.p(V5,g.W);
V5.prototype.C=function(){this.o||(this.o=new g.wG(g.Y(this.B).Bf));var a={context:g.jG(this.o.g)};if(this.l.isToggled){a.params=this.l.toggledServiceEndpoint.removeUpcomingEventReminderEndpoint.params;var b="notification/remove_upcoming_event_reminder"}else a.params=this.l.defaultServiceEndpoint.addUpcomingEventReminderEndpoint.params,b="notification/add_upcoming_event_reminder";var c={timeout:5E3};c.onError=(0,g.z)(this.A,this);c.xd=(0,g.z)(this.A,this);g.kG(this.o,b,a,c);this.l.isToggled=!this.l.isToggled;
W5(this)};
V5.prototype.A=function(){this.l&&(this.l.isToggled=!this.l.isToggled,W5(this))};g.p(X5,g.W);
X5.prototype.C=function(a){var b=a&&a.liveStreamability&&a.liveStreamability.liveStreamabilityRenderer.offlineSlate;if(b){this.l=a;b.liveStreamOfflineSlateRenderer.canShowCountdown?this.D():Y5(this,b.liveStreamOfflineSlateRenderer);var c=this.element;if(b&&b.liveStreamOfflineSlateRenderer&&b.liveStreamOfflineSlateRenderer.scheduledStartTime){var d=b.liveStreamOfflineSlateRenderer.scheduledStartTime-(0,g.G)()/1E3;d=86400>=d&&86340<d}else d=!1;g.T(c,"ytp-offline-slate-show-final-day",d);if(c=a&&a.liveStreamability&&
a.liveStreamability.liveStreamabilityRenderer&&a.liveStreamability.liveStreamabilityRenderer.offlineSlate&&a.liveStreamability.liveStreamabilityRenderer.offlineSlate.liveStreamOfflineSlateRenderer&&a.liveStreamability.liveStreamabilityRenderer.offlineSlate.liveStreamOfflineSlateRenderer.thumbnail){d=0;for(var e=null,f=0;f<c.thumbnails.length;f++)c.thumbnails[f].width>d&&(d=c.thumbnails[f].width,e=c.thumbnails[f].url);e&&(this.element.style.backgroundImage="url("+e+")")}else this.element.style.backgroundImage=
"";b.liveStreamOfflineSlateRenderer.actionButtons?(this.A||(this.A=new V5(this.o),this.A.va(this.sa["ytp-offline-slate-buttons"]),g.M(this,this.A)),CAa(this.A,b.liveStreamOfflineSlateRenderer.actionButtons[0])):this.A&&CAa(this.A,null);this.l=a}else this.l=null;this.F()};
X5.prototype.F=function(){var a=g.UU(this.o),b=this.o.ea(),c=b.za&&(g.fP(a)||g.X(a,2)||g.X(a,64));a=a.kb()&&!g.pO(b)&&!this.o.isPeggedToLive(!0);c&&!a&&this.l&&"LIVE_STREAM_OFFLINE"==this.l.status.toUpperCase()?this.g||(this.show(),this.o.R("offlineslatestatechange")):this.g&&(this.hide(),this.o.R("offlineslatestatechange"))};
X5.prototype.D=function(){var a=this.l&&this.l.liveStreamability&&this.l.liveStreamability.liveStreamabilityRenderer&&this.l.liveStreamability.liveStreamabilityRenderer.offlineSlate&&this.l.liveStreamability.liveStreamabilityRenderer.offlineSlate.liveStreamOfflineSlateRenderer;if(a){var b=Math.floor((0,g.G)()/1E3),c=a.canShowCountdown&&(0,window.parseInt)(a.scheduledStartTime,10);!c||c<=b?(Y5(this,a),this.B.stop()):(b=g.FV(c-b),Y5(this,a,b),g.Zt(this.B))}};
X5.prototype.V=function(){this.B.dispose();this.B=null;g.W.prototype.V.call(this)};g.p($5,g.rV);g.h=$5.prototype;g.h.V=function(){c6(this);g.jV(this.g,"heartbeat");g.rV.prototype.V.call(this)};
g.h.KL=function(){this.H=!0;Z5(this,2E3)};
g.h.LL=function(a){this.A=a;Z5(this,2E3)};
g.h.ML=function(a){g.X(a.state,2)||g.X(a.state,64)?(c6(this),this.B&&(this.H=!0,Z5(this,1E3))):(g.X(a.state,1)||g.X(a.state,8))&&Z5(this,2E3)};
g.h.sT=function(){3!==this.g.Sa()&&Z5(this,2E3)};
g.h.xU=function(){var a=g.Y(this.g),b=this.g.ea();var c=a.baseYtUrl;if(3==this.g.Sa())this.l=window.NaN;else if(g.X(g.UU(this.g),4))this.l=window.NaN;else if(a6(this)||b.za){if(!GAa(this)||b.za){var d="GET";var e=a.A;a={video_id:b.videoId,heartbeat_token:b.heartbeatToken,c:e.c,cver:e.cver,cbrand:e.cbrand,cmodel:e.cmodel,vvt:b.kg,mdx_environment:b.mdxEnvironment,access_token:b.oauthToken,forced_experiments:a.forcedExperiments,utc_offset_minutes:this.K};(e=g.bO(b))&&(a.uloc=e);(e=this.g.wh().ingestionTime)&&
(a.ingestion_time=e);c=g.Sg(c+"heartbeat",a)}else d="GET",c=g.Sg(this.A.url,{request_id:g.LG()}),b.kg&&(c=g.Sg(c,{vvt:b.kg}),b.mdxEnvironment&&(c=g.Sg(c,{mdx_environment:b.mdxEnvironment}))),b.oauthToken&&(c=g.Sg(c,{access_token:b.oauthToken}));b.ul&&(c=g.Sg(c,{internalipoverride:b.ul}));c=g.Sg(c,{cpn:b.clientPlaybackNonce});g.qE(c,{format:"RAW",method:d,timeout:3E4,Jb:(0,g.z)(this.RK,this),onError:(0,g.z)(this.QK,this),xd:(0,g.z)(this.SK,this),withCredentials:!0})}else c6(this)};
g.h.RK=function(a){if(this.l){a=a.responseText;var b=HAa(a);if(b){this.g.ua("onHeartbeat",b);var c="ok"==b.status?b.stop_heartbeat?2:0:"stop"==b.status?1:"live_stream_offline"==b.status?0:-1}else c=(c=a.match(IAa))?"0"==c[1]?0:1:-1;if(-1==c)b6(this,!1,"decode");else if(2!=c||a6(this))if(this.I=0,this.l=window.NaN,1==c){this.F=!1;b=this.g;c="YTP_ERROR_LICENSE";var d=HAa(a);d?a=d.reason||g.V(c):((a=a.match(IAa))&&(a=(0,window.parseInt)(a[1],10))&&(c=g.AO(a)),a=g.V(c));g.hU(b.app.o,"heartbeat.stop",
a,void 0)}else this.F=!0,a=0,this.B&&b&&(a=FAa(this,b),this.g.R("livestatedata",b)),a?Z5(this,a):Z5(this);else c6(this),this.F=!0}};
g.h.QK=function(a){b6(this,!0,"net-"+a.status)};
g.h.SK=function(){b6(this,!0,"timeout")};
g.h.JL=function(){return!!this.D&&this.D.g};
var IAa=/^GLS\/1.0 (\d+) (\w+).*?\r\n\r\n([\S\s]*)$/;g.fY.heartbeat=$5;})(_yt_player);
